# build and test

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'

- script: |
    go version
    mkdir bin/
    cd cmd/prom-aggregation-gateway
    go build -o prom-aggregation-gateway
  displayName: 'Get dependencies, then build'

